version: '3.8'

services:
  neo4j:
    image: neo4j:5.15
    container_name: neo4j-database
    restart: unless-stopped
    ports:
      - "7474:7474"   # HTTP
      #      - "7473:7473"   # HTTPS
      - "7687:7687"   # Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      # Enable multiple databases
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_dbms_databases_default__to__read__only=false
      # Web interface configuration
      - NEO4J_dbms_connector_http_enabled=true
      #      - NEO4J_dbms_connector_https_enabled=true
      - NEO4J_dbms_connector_bolt_enabled=true
      # Security and access configuration
      - NEO4J_dbms_connector_http_listen__address=0.0.0.0:7474
      #      - NEO4J_dbms_connector_https_listen__address=0.0.0.0:7473
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
      # Memory settings (adjust based on your system)
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
      # Additional security settings
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*,apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
      - neo4j_conf:/conf
    networks:
      - neo4j_network

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  neo4j_conf:

networks:
  neo4j_network:
    driver: bridge


# Neo4j Authentication
  NEO4J_USERNAME=neo4j
  NEO4J_PASSWORD=OssracF1982

# Optional: Change these if you need different ports
# NEO4J_HTTP_PORT=7474
# NEO4J_HTTPS_PORT=7473
# NEO4J_BOLT_PORT=7687
