<div x-data="timelineComponent({
            minFrame: {{$timeline['config']['minFrame']}},
            maxFrame: {{$timeline['config']['maxFrame']}},
            frameToPixel: {{$timeline['config']['frameToPixel']}},
            labelWidth: {{$timeline['config']['labelWidth']}}
    })" class="timeline">
    <div class="container">
        <!-- Controls -->
        <div class="controls">
            <div class="ui medium input">
            <label>Go to frame:
                <input
                    type="number"
                    id="frame-input"
                    value="0"
                    min="0"
                    max="{{$timeline['config']['maxFrame']}}"
                    x-model="frameInput"
                    @keydown.enter="scrollToFrame()"
                >
            </label>
            </div>
            <button class="ui tiny button" @click="scrollToFrame()">Go</button>
            <button class="ui tiny button" @click="scrollToStart()">Start</button>
            <button class="ui tiny button" @click="scrollToEnd()">End</button>
            <button class="ui tiny button" @click="scrollToVideoFrame()">as Video</button>
            <span class="invisible" id="current-frame">Frame: 0</span>
        </div>

        <!-- Ruler -->
        <div class="ruler">
            <div class="label-area">
                Layers
            </div>
            <div class="content-area">
                <div class="content" id="ruler-content">
                    <!-- Ruler ticks will be generated by JavaScript -->
                </div>
            </div>
        </div>

        <!-- Main content area -->
        <div class="main">
            <!-- Labels column -->
            <div class="labels-column" id="labels-column">
                @foreach ($groupedLayers as $visualLayer)
                    @php $layerHeight = count($visualLayer['lines']) * $timeline['config']['objectHeight']; @endphp
                    <div class="label-item" style="height: {{ $layerHeight }}px;">
                        {{ $visualLayer['name'] }}
                    </div>
                @endforeach
            </div>
            <!-- Timeline content -->
            <div class="content" id="timeline-content" style="">
                <div class="inner" style="width: {{ $timeline['config']['timelineWidth'] }}px;">
                    @foreach ($groupedLayers as $visualLayerIndex => $visualLayer)
                        @php
                            $layerHeight = count($visualLayer['lines']) * $timeline['config']['objectHeight'];
                        @endphp
                        <div class="layer-row" style="height: {{ $layerHeight }}px;">
                            <!-- Layer Objects -->
                            <div class="objects" style="height: {{ $layerHeight }}px;">
                                @foreach ($visualLayer['lines'] as $lineIndex => $line)
                                    @foreach ($line['objects'] as $objIndex => $object)
                                        @php
                                            $startPos = ($object->startFrame - $timeline['config']['minFrame']) * $timeline['config']['frameToPixel'];
                                            $duration = $object->endFrame - $object->startFrame;
                                            $width = max($timeline['config']['minObjectWidth'], $duration * $timeline['config']['frameToPixel']);
//                                            $bgColor = $object->bgColorGL ?? '#999999';
//                                            $label = $object->gl ?? $object->luName ?? $object->name ?? "Object " . ($objIndex + 1);
                                            $bgColor = $object->bgColor;
                                            $fgColor = $object->fgColor;
                                            $label = $object->name;
                                            $top = $lineIndex * $timeline['config']['objectHeight'];
                                            $tooltip = $label . "\nFrames: " . $object->startFrame . "-" . $object->endFrame . "\nDuration: " . $duration . " frames";
                                        @endphp
                                        <div class="object"
                                             style="left: {{ $startPos }}px; top: {{ $top }}px; width: {{ $width }}px; background-color: {{ $bgColor }};color: {{$fgColor}}"
                                             title="{{ $tooltip }}"
                                             data-layer-index="{{ $line['originalIndex'] }}"
                                             data-object-index="{{ $objIndex }}"
                                             data-line-index="{{ $lineIndex }}"
                                             data-start-frame="{{ $object->startFrame }}"
                                             data-end-frame="{{ $object->endFrame }}"
                                             hx-get="/annotation/deixis/object/{{$object->idDynamicObject}}"
                                             hx-target="#formsPane"
                                             hx-swap="innerHTML"
                                        >
                                            {{ $label }}
                                        </div>
                                    @endforeach
                                @endforeach
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>

        <!-- Info bar -->
        <div class="info" id="timeline-info">
            Timeline ready - scroll to navigate
        </div>
    </div>
</div>

<!-- Dynamic Content Areas -->
<div id="highlight-container"></div>
<div id="object-click-info"></div>

